name: deploy-book

# Ejecutar cuando se realicen cambios en las ramas `main` o `master`
on:
  push:
    branches:
      - main
      - master

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # Instalar Python
      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # Instalar dependencias
      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      # Cachear notebooks ejecutados (opcional)
      - name: Cache de notebooks ejecutados
        uses: actions/cache@v4
        with:
          path: _build/.jupyter_cache
          key: jupyter-book-cache-${{ hashFiles('requirements.txt') }}

      # Construir el Jupyter Book
      - name: Construir el libro
        run: |
          jupyter-book build .

      # Verificar si la carpeta _build/html fue creada correctamente
      - name: Verificar carpeta de salida
        run: |
          if [ ! -d "_build/html" ]; then
            echo "Error: La carpeta _build/html no se generó correctamente."
            exit 1
          fi

      # Subir el HTML como artefacto
      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_build/html"

      # Desplegar en GitHub Pages
      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
